trigger:
  - master

# 1. Volvemos a conectar tu caja fuerte para que lea el token de despliegue
variables:
  - group: VCwebDS3-Variables

pool:
  vmImage: ubuntu-latest

steps:
  - task: AzureStaticWebApp@0
    inputs:
      app_location: '/'
      output_location: 'dist'
      azure_static_web_apps_api_token: $(FRONTEND_DEPLOY_TOKEN)
    env:
      # 2. LA CLAVE: Forzamos a Azure a usar Node 20 para que Vite no falle
      NODE_VERSION: '20.x'
      
      VITE_FIREBASE_API_KEY: $(VITE_FIREBASE_API_KEY)
      VITE_FIREBASE_AUTH_DOMAIN: $(VITE_FIREBASE_AUTH_DOMAIN)
      VITE_FIREBASE_PROJECT_ID: $(VITE_FIREBASE_PROJECT_ID)
      VITE_FIREBASE_STORAGE_BUCKET: $(VITE_FIREBASE_STORAGE_BUCKET)
      VITE_FIREBASE_MESSAGING_SENDER_ID: $(VITE_FIREBASE_MESSAGING_SENDER_ID)
      VITE_FIREBASE_APP_ID: $(VITE_FIREBASE_APP_ID)
    displayName: 'Compilar y Desplegar Frontend en Azure'
